project:
  type: book

book:
  title: "Hurtownie danych oraz analityczne metody przetwarzania"
  author: "≈Åukasz Wawrowski"
  date: ""
  chapters:
    - index.qmd
    - 00-organizacja.qmd
    
format:
  html:
    theme:
      - cosmo
      - brand
