project:
  type: book

book:
  title: "Hurtownie danych i analityczne metody przetwarzania"
  author: "Łukasz Wawrowski"
  date: ""
  chapters:
    - index.qmd
    - 00-organizacja.qmd
    
format:
  html:
    toc-title: "Spis treści"
    theme:
      - cosmo
      - brand
